[package]
name = "rusty-wumpus"
version = "0.1.0"
authors = ["Thomas Kiley <thomas.kiley@diffblue.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
